### ISSUE TITLE
Should the pre-submission letter include explicit commitments to update?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#177]
Should the pre-submission letter include explicit commitments to update, either from the authors, or from collaborators the lined up?  And should it explicitly discuss things that might be in an update?

**Comment by davidlmobley** [comment]
No, not in my opinion. We already have a procedure in the guidelines for what happens if people don't update, and people are implicitly agreeing to update.

**Comment by dmzuckerman** [comment]
> people are implicitly agreeing to update

As we broaden our authorship group, which we hope to do, folks will have less familiarity with all the  points we have discussed in detail and which are somewhat buried on the website - the website has a lot of info!

Perhaps 'commitment' is a strong word but what about asking authors to state that they understand the expectation that articles will be updated?  It would be better to have this out in the open rather than having to initiate an 'abandoned' paper process, in my view.

**Comment by dmzuckerman** [comment]
Good idea. @davidlmobley ?

**Comment by davidlmobley** [comment]
Yes, I like this idea; the pre-submission letters should ideally have such a section.

**Comment by mrshirts** [comment]
OK, suggestion in as a PR #181.  Not sure if I struck the right tone or not.

**Comment by mrshirts** [comment]
PR #181 was merged, closing issue.
