### ISSUE TITLE
Add editorial policy on civility on GitHub discussions

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#21]
We should be clear in our policies/reviewer/editor comments on how to be civil when disagreeing. For example, an xplicit code of conduct for all. Can consult existing codes of conduct (http://www.mdanalysis.org/pages/conduct/), especially in terms of how community should provide feedback to authors via GitHub.

This also relates to authors in teaching how to “teach the controversy," for example, for best practices, what happens when there are not best practices?

**Comment by davidlmobley** [comment]
Do we really need to have a code of conduct? And, if we had one, could we DO anything to enforce it even if we wanted to? We are not managing a discussion forum or anything similar; people will have discussions via GitHub, but that's not under our jurisdiction (we don't serve as moderators, and in fact CAN'T moderate comments unless authors make us admins on their repos). 

I think if we WANT to encourage people to have a code of conduct the thing to do would be to put a template "code of conduct" in the templates repo which has some of this type of material so that when people initialize their paper repos they will contain a code of conduct. But it's not something we're going to be able to deal with ourselves, I don't think.

**Comment by dmzuckerman** [comment]
I agree.
________________________________

**Comment by davidlmobley** [comment]
Closing for now.
