### ISSUE TITLE
What is the mechanism to determine author order?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#25]
The main consideration is how to ensure that individuals get appropriate credit. Do we specifically list contributions of each author in the article (probably).  Do we designate specific corresponding author(s)?  Do we Distinguish only between “current authors/maintainers” and “contributors”?

Maybe (For initial batch of papers) list every author as corresponding author in (reverse) alphabetical order?

What is the mechanism for disputing?

**Comment by dmzuckerman** [comment]
Author contributions should definitely be listed, especially since a new author may come on board and contribute equally to prior authors ... likely in Lessons Learned category (I hope).

We may want to have special designations for first/primary authors and corresponding/directing authors.  We need our authors to be able to get regular academic credit.  Imagine a tenure committee one day checking on someone's CV.

**Comment by davidlmobley** [comment]
The obvious categories are:
- authors (with contributions listed)
- acknowledgments (with contributions listed)

But, I think I also like the idea of (at least recommending) a "current maintainers" category which might diverge from the authors list or at least be a subset thereof. This would help maintainers avoid/work around the issue of "so and so doesn't really want to be involved with approving updates anymore but still deserves authorship on the basis of past work".

Should we also recommend that all authors be "corresponding" in the sense of "their e-mail address is listed"? It just seems like it would be clearest to be **explicit** about everyone's contributions rather than using "corresponding" as proxy for "supervised the work" when it may or may not mean that (especially here when there typically will not be "work" that was "supervised" except perhaps in the case of "things that didn't work").

**Comment by mrshirts** [comment]
I agree with being more explicit and more transparent about peoples contributions.  We can have a little section like some journals do saying which people did which things, though we may need to invent some more categories than "carried out experiments", "designed experiments", "wrote paper", etc.

**Comment by davidlmobley** [comment]
I think we just tell people to be descriptive rather than using categories. This is all electronic, so there is no length limit. We can put comments in the LaTeX template saying this.

(I think it's logical to also have this info in the README.md in the GitHub repo of hte paper since it's even more prominent there.)

**Comment by dmzuckerman** [comment]
I do feel we need to have explicit categories for 'first' and 'corresponding' authorship.  Our authors must have verifiable academic credit - i.e., when a potential postdoc supervisor or tenure committee clicks on a link to livecoms, the journal must be able to confirm the claim of authorship level.  If we don't have this, I could see hesitation to submit.

Do you guys agree?

**Comment by davidlmobley** [comment]
@dmzuckerman - that's an excellent point. In part you are pointing out that there are two issues here:
a) What is done on the GitHub repo and in the PDF itself, and
b) What we actually indicate in the LiveCoMS publication system, citation, etc.

I've been focused on (a), but you're right that we need to also address (b). My suggestion would be:
For (a), do as I've been suggesting above and explicitly document each person's contribution. BUT, we will also need to designate a formal corresponding author or authors. And then for (b), in the actual citation, we formally indicate corresponding authors.

This way, supervisors and tenure committees who only understand the "old system" (current system) can use the normal way of assessing things and people who know what we're doing can actually just read the descriptions of what people did. Does that make sense?

**Comment by mrshirts** [comment]
Put a place for this policy in https://github.com/livecomsjournal/journal_information/pull/25. Mostly a stub for now.

**Comment by davidlmobley** [comment]
I think this is resolved by the "author order" section at https://livecomsjournal.github.io/policies/; it can be reopened if needed. Our current approach (which I am very happy with) is to leave this to the authors to sort out amongst themselves, which is what people are used to doing so it should work well.
