### ISSUE TITLE
Need a few different editorial board policies

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#31]
Examples policies that are needed:

- [x] How to add new members 
- [x] What if there are disagreements 
- [x] Who controls money.

**Comment by davidlmobley** [comment]
Seems like the third of those requires resolution of the issue of whether there is going to be an umbrella organization or whether it's all being run through CU, which is also connected to the legal issues.

On how to add new members: I'll propose majority vote of the existing board (or at least, those of the board responding within an X day window).
On what if there are disagreements: Disagreements on what? Are you thinking how we decide issues (e.g. by vote) or if there are conflicts?

**Comment by mrshirts** [comment]
Yes, we still need to work out the money issues - we don't have 

Do we want to have a .md file that has editorial policies, or keep them on some other document?  I can create that if needed. 

> Disagreements on what? Are you thinking how we decide issues (e.g. by vote) or if there are conflicts?

Yes, any decision that needs to be made -- if we do decide to join some existing organization, any of the policies for papers, policies regarding what license we accept -- there could be a number of them. I suspect that majority vote is fine, but we just need for formalize that so there is a process.

**Comment by davidlmobley** [comment]
> Do we want to have a .md file that has editorial policies, or keep them on some other document? I can create that if needed.

I tend to think editorial policies should be in a relatively formal document, so perhaps LaTeX leading to a PDF that would get posted in "editorial material" on the LiveCoMS journal site. 

> Yes, any decision that needs to be made -- if we do decide to join some existing organization, any of the policies for papers, policies regarding what license we accept -- there could be a number of them. I suspect that majority vote is fine, but we just need for formalize that so there is a process.

My suggestion:
- Issues regarding governance structure, leadership, and our financial model need to be decided by a 2/3 majority vote of the editorial board`*`
- Other issues are decided by a simple majority vote of the editorial board`*` (e.g. editorial policy, licensing policy, etc.)
- Are there exceptions? e.g. should editors be able to be added or removed based on managing editor discretion, or...? (Naively it seems like not).

`*` - votes are tallied based on the fraction of the editorial board responding within one week written notice via e-mail. In exceptional circumstances advance notice may be given of a rush decision, where the board may be given one week (or more) notice that their votes will be needed within a shorter window, such as a 12 hour window.

**Comment by mrshirts** [comment]
> I tend to think editorial policies should be in a relatively formal document, so perhaps LaTeX leading to a PDF that would get posted in "editorial material" on the LiveCoMS journal site.

Agreed.  I'll start working on a draft.

**Comment by mrshirts** [comment]
Started a document on this at https://github.com/livecomsjournal/journal_information/pull/25

**Comment by davidlmobley** [comment]
The current draft, @mrshirts , doesn't say anything about money. What's the status on that aspect?

**Comment by mrshirts** [comment]
How money is handled will depend a bit on governance structure and who the "publisher" actually is, so I'm still looking around at this.

**Comment by dmzuckerman** [comment]
Not sure if this is the right place for this, but somewhere we should have a policy indicating that an editor should recuse her/himself from overseeing a submission where there is an appearance of conflict of interest.  (My group may have a nice "Lessons Learned" to submit ... and obviously I can't be in charge of that!)

**Comment by mrshirts** [comment]
>  for this, but somewhere we should have a policy indicating that an editor should recuse her/himself from overseeing a submission where there is an appearance of conflict of interest.

Yes, this could be stated explicitly here.  Scholastica does have a way to do this.  Once an article is assigned, you can select if other editors should have that article blinded from them.  Default is all editors can see everything, but can do exclusions.

**Comment by oostenbrink** [comment]
I'm not sure if I have found all issues concerning the editorial policy and if this is the place to add my two cents of thoughts here. As I am new to all this, I apologize if I am bringing up topics that have been covered long ago already.

I guess what we need is a document that somehow outlines the duties and rights of the editors. It would typically be something that you never hope to use, but that also takes care of situations when people are not agreeing so much with each other. Does the publisher have something to say about this? I guess they put the responsibility with one or a few main editors and don't care too much about the rest of the editorial board? This means that the decision power should also reflect this?

We should think about the kind of decisions that need to be made and something will need to be said about all of these in the editorial policy.
1. - Assignment of a work to an editor. Solely based on where the authors sends the presubmission letter, or does someone look at this? How do we prevent 'editor hopping' if the authors gets a discouraging response? In traditional journals there is usually an editor in chief who does this, right? Or would this be the lead editors for any specific kind of contribution?
2. - Conflicts of interest. As mentioned above, an editor should not be in charge of his/her own manuscript, or manuscripts of 'close friends'. Do we need to formalize what counts as a close friend?
3. - Editorial decisions. The editor decides on encouragements or discouragements after the presubmission letter, the editor decides on the reviewers to invite and also makes a final decision on acceptance or not. This is clear, but what happens if the authors complain to other editors because they thought the decision was inappropriate? Is there an editor in chief that can overrule the decision of the original editor, do we create a system of getting a 'second opinion' or do we just ignore complaints? Such complaints will come.
4. - How are the difficult decisions made? We find a case of plagiarism or construction of fake data, a manuscript slips through that is insulting or even calling for violence. Should it be removed, or not? Who decides that? A single editor, the managing editors, a majority vote? Will we be hosting LiveCoMS discussion boards along with the works? Then the same kind of decisions will have to be made here. Can abusive comments be reported (to whom) and can they be removed?
5. - Decisions on a revision of the editorial policy, the licensing policy, revisions of the guidelines to authors, can be discussed by a majority vote.
6. - Big decisions on the future of the governance structure, editorial board membership, leadership, and financial model must be decided by a 2/3 majority vote of those members of the editorial board who vote on the issue. These are things that probably need to be discussed with the publisher and some lawyer? What will the publisher say if some day, a 2/3 majority decides to throw Michael out? Is UC then still interested at all?

These last two issues are already covered in the current text. A question is maybe if there should be guidance as to who can bring these decisions to a vote. Only the managing editors, only the lead editors, any member of the editorial board?

Rather than using voting by e-mail, I would suggest to use some online voting tool. These send an e-mail with a clear question and then you can click on yes or no, or whatever other options are offered. Then you are sure you get a clear vote and not a long e-mail with with opinions and contrasting answers, where you can read out whatever you like. These services typically also provide some protocol of the vote to keep for the future. And it allows you to make anonymous votes (but still only the right people are allowed to vote). The editorial policy should offer guidance at times when people do not agree or when there is frustration between editors. Then I guess it is safe to be clear.

My first contribution here seems to paint a rather dark picture of future scenarios. Sorry for that. I really won't suggest to throw out Michael.

**Comment by oostenbrink** [comment]
Two more kinds of decisions that we probably want to put down a policy for:
a. The reviewers are asked to also comment on the formatting, spelling, grammar etc. We write that 'Authors whose article uses inconsistent style or poor grammar, or is poorly edited, may be asked to revise and address these issues.' What happens if we cannot reach an agreement? Is this up to the handling editor to just keep refusing to accept it, if the authors think it is good enough? What about contributors for whom English is not their native language? Do we care about that? Are we going to correct manuscripts ourselves? It is probably good to think about how we plan to enforce this.

b. The decision making around 'abandoned manuscript' may also call for difficult decisions. In general the authors will want to update a review themselves, but maybe they don't have time. What if there is another person who is eager to take over, but the original authors think they will have time for this in a couple of months (which never comes). Even if a CC-BY license allows for this, I don't think it is considered decent to take a review, modify it (significantly), add your own name to it and republish it. Particularly not if the original authors oppose this idea. We should have some thoughts on how to deal with this.

**Comment by mrshirts** [comment]
> I'm not sure if I have found all issues concerning the editorial policy and if this is the place to add my two cents of thoughts here. As I am new to all this, I apologize if I am bringing up topics that have been covered long ago already.

Hi, Chris- Thanks for all the thoughts. We have not spent as much time on the templates and instructions, so it's good to get this explicitly discussed.

Also: I'm going to break this up into a few comments after I post, so don't respond for 5 min or so.
> I guess what we need is a document that somehow outlines the duties and rights of the editors. It would typically be something that you never hope to use, but that also takes care of situations when people are not agreeing so much with each other. 

We've been thinking pretty much just about the policies we need to make these sorts of decisions.

> Does the publisher have something to say about this? I guess they put the responsibility with one or a few main editors and don't care too much about the rest of the editorial board? This means that the decision power should also reflect this?

Not really. CU Boulder is serving as the publisher, but the lawyer advising us isn't making any demands/requests about the editorial policies.

> We should think about the kind of decisions that need to be made and something will need to be said about all of these in the editorial policy.

I think one question is the right place to put this; whether it's in the editorial policy page or not.  Regardless, it does need to be somewhere, so good to get this out.

> Assignment of a work to an editor. Solely based on where the authors sends the presubmission letter, or does someone look at this? How do we prevent 'editor hopping' if the authors gets a discouraging response? In traditional journals there is usually an editor in chief who does this, right? Or would this be the lead editors for any specific kind of contribution?

I think it would be done by the lead editor of a section.  If it looks like it should be submitted to another section, it should be sent there. 

> Conflicts of interest. As mentioned above, an editor should not be in charge of his/her own manuscript, or manuscripts of 'close friends'. Do we need to formalize what counts as a close friend?

That's a great question.  Obviously, no dealing with one's own manuscripts.  Perhaps we make it a self-policing policy on editorial assignment right now?  I'm open to other suggestions.

> Editorial decisions. The editor decides on encouragements or discouragements after the presubmission letter, the editor decides on the reviewers to invite and also makes a final decision on acceptance or not. This is clear, but what happens if the authors complain to other editors because they thought the decision was inappropriate? Is there an editor in chief that can overrule the decision of the original editor, do we create a system of getting a 'second opinion' or do we just ignore complaints? Such complaints will come.

We do need a system.  I would rather have a system of a group of editors (perhaps 3?) than a single chief editor decide.  And formalize why it's turned down - only turned down where the policies are not followed?

> How are the difficult decisions made? We find a case of plagiarism or construction of fake data, a manuscript slips through that is insulting or even calling for violence. Should it be removed, or not? Who decides that? A single editor, the managing editors, a majority vote? 

> Will we be hosting LiveCoMS discussion boards along with the works? Then the same kind of decisions will have to be made here. Can abusive comments be reported (to whom) and can they be removed?

Great question.  I think our decisions was that discussions about the manuscript would be hosted on GitHub, centered on that manuscript itself, not on any larger issues.  This comment here reinforces that idea -- we don't want to host a central one, we just want to have people discuss their own manuscripts.

> Decisions on a revision of the editorial policy, the licensing policy, revisions of the guidelines to authors, can be discussed by a majority vote. Big decisions on the future of the governance structure, editorial board membership, leadership, and financial model must be decided by a 2/3 majority vote of those members of the editorial board who vote on the issue. 

> These are things that probably need to be discussed with the publisher and some lawyer? What will the publisher say if some day, a 2/3 majority decides to throw Michael out? Is UC then still interested at all?

Once we have done these governance things, the lawyer at CU will look over it to see if there are any blatant issues.  My memo to the Provost discusses as succession plan, though it only covers if I leave CU.   It's much easier to start with CU's backing for the first few years.  CU isn't providing any funding (the CU library is, but that's a 1 time thing independent of the publishing). They aren't that invested in directing the effort (as long as it doesn't cause them a headache) - they are just seeing it as a nice thing that a professor is doing that will bring a small bit of positive press to the school.  I think that we do want to think about eventually moving to a different publisher; either a 501(c)(3) created for this, or some other organization.

> These last two issues are already covered in the current text. A question is maybe if there should be guidance as to who can bring these decisions to a vote. Only the managing editors, only the lead editors, any member of the editorial board?

I would say any member of the editorial board.

> Rather than using voting by e-mail, I would suggest to use some online voting tool. These send an e-mail with a clear question and then you can click on yes or no, or whatever other options are offered. Then you are sure you get a clear vote and not a long e-mail with with opinions and contrasting answers, where you can read out whatever you like. 

Is this necessary?  We can simply say: Votes must be yes or no, or they are not counted.

> These services typically also provide some protocol of the vote to keep for the future. And it allows you to make anonymous votes (but still only the right people are allowed to vote). The editorial policy should offer guidance at times when people do not agree or when there is frustration between editors. Then I guess it is safe to be clear.

I don't know that we need to keep the vote in history;  If the votes are sent to the entire editorial board, then it's very clear who voted or not, any anyone can make sure the count was done correctly.  If we want to anonymous, then that is different - we would need software.  I don't know that we need it anonymous for now?  I would like to hear other people's thoughts.

If you have suggestions for such software, however, definitely let us know!

> My first contribution here seems to paint a rather dark picture of future scenarios. Sorry for that. I really won't suggest to throw out Michael.

Important to bring these issues up now rather than later!

**Comment by mrshirts** [comment]
> Rather than using voting by e-mail, I would suggest to use some online voting tool. These send an e-mail with a clear question and then you can click on yes or no, or whatever other options are offered. Then you are sure you get a clear vote and not a long e-mail with with opinions and contrasting answers, where you can read out whatever you like.

Is this necessary? We can simply say: Votes must be yes or no, or they are not counted.

> These services typically also provide some protocol of the vote to keep for the future. And it allows you to make anonymous votes (but still only the right people are allowed to vote). The editorial policy should offer guidance at times when people do not agree or when there is frustration between editors. Then I guess it is safe to be clear.

I don't know that we need to keep the vote in history; If the votes are sent to the entire editorial board, then it's very clear who voted or not, any anyone can make sure the count was done correctly. If we want to anonymous, then that is different - we would need software. I don't know that we need it anonymous for now? I would like to hear other people's thoughts.

If you have suggestions for such software, however, definitely let us know!

**Comment by mrshirts** [comment]
> Editorial decisions. The editor decides on encouragements or discouragements after the presubmission letter, the editor decides on the reviewers to invite and also makes a final decision on acceptance or not. This is clear, but what happens if the authors complain to other editors because they thought the decision was inappropriate? Is there an editor in chief that can overrule the decision of the original editor, do we create a system of getting a 'second opinion' or do we just ignore complaints? Such complaints will come.

We do need a system.  I would rather have a system of a group of editors (perhaps 3?) than a single chief editor decide.  And formalize why it's turned down - only turned down where the policies are not followed?

> How are the difficult decisions made? We find a case of plagiarism or construction of fake data, a manuscript slips through that is insulting or even calling for violence. Should it be removed, or not? Who decides that? A single editor, the managing editors, a majority vote? 

Fake data or plagarism could probably be voted on by the board, with a smaller group investigating. In terms of insulting or calling for violence ; this should generally be caught at editorial time; if not, we probably should reserve the right to take a paper offline for while.

**Comment by mrshirts** [comment]
> Assignment of a work to an editor. Solely based on where the authors sends the presubmission letter, or does someone look at this? How do we prevent 'editor hopping' if the authors gets a discouraging response? In traditional journals there is usually an editor in chief who does this, right? Or would this be the lead editors for any specific kind of contribution?

I think it would be done by the lead editor of a section.  If it looks like it should be submitted to another section, it should be forwarded to that lead editor.  They would essentially serve as editor-in-chief for those sections.

**Comment by mrshirts** [comment]
> Conflicts of interest. As mentioned above, an editor should not be in charge of his/her own manuscript, or manuscripts of 'close friends'. Do we need to formalize what counts as a close friend?

That's a great question.  Obviously, no dealing with one's own manuscripts; when received by the lead editor, they should hand it to another editor, and get blinded. Perhaps we make it a self-policing policy on editorial assignment right now?  I'm open to other suggestions.

**Comment by mrshirts** [comment]
> Will we be hosting LiveCoMS discussion boards along with the works? Then the same kind of decisions will have to be made here. Can abusive comments be reported (to whom) and can they be removed?

Great question.  I think our decisions was that discussions about the manuscript would be hosted on GitHub, centered on that manuscript itself, not on any larger issues.  This comment here reinforces that idea -- we don't want to host a central one, we just want to have people discuss their own manuscripts.  Other people's thoughts?

**Comment by mrshirts** [comment]
> The decision making around 'abandoned manuscript' may also call for difficult decisions. In general the authors will want to update a review themselves, but maybe they don't have time. What if there is another person who is eager to take over, but the original authors think they will have time for this in a couple of months (which never comes). Even if a CC-BY license allows for this, I don't think it is considered decent to take a review, modify it (significantly), add your own name to it and republish it. Particularly not if the original authors oppose this idea. We should have some thoughts on how to deal with this.

We have talked about this.  And I think we do have to make a firm policy that if it's left alone for some period of time (3 years?), then they have to hand it off if they are not updating.  We just can't surprise them with this - they have to expect it. We can clarify this so there is several chances.

**Comment by mrshirts** [comment]
>The reviewers are asked to also comment on the formatting, spelling, grammar etc. We write that 'Authors whose article uses inconsistent style or poor grammar, or is poorly edited, may be asked to revise and address these issues.' What happens if we cannot reach an agreement? Is this up to the handling editor to just keep refusing to accept it, if the authors think it is good enough? What about contributors for whom English is not their native language? Do we care about that? Are we going to correct manuscripts ourselves? It is probably good to think about how we plan to enforce this.

I think this is good point.  We won't correct them ourselves (beyond what reviewers are willing to do). Other journals have suggestions about hiring a professional editor, we can copy that language.  Thoughts, other people?

**Comment by dmzuckerman** [comment]
@oostenbrink - Great comments.  Thank you so much for taking the time.  I'll add a few thoughts here, especially regarding queries left by @mrshirts .

For purposes of organizing the website, I think there should be one editorial policies doc with ALL issues pertinent to authors, and a separate one pertinent ONLY to internal governance (e.g., getting rid of Michael ... or me, policy for changing policies). 

I agree with the suggestion to use an online tool for voting.  This outsources/eliminates problems with deadlines, counting (no surprises - if some editors REPLY vs REPLY ALL) and also allows for anonymity.  Of course the issue of anonymous voting should be in the governance doc.

Regarding appeal of editorial decisions, we want to make that hard.  Note that if 2 of 3 'appeal board' editors approve, that's still a 2-2 tie of editors if we include the original one.  So in terms of arithmetic we could have a 2-person review and require unanmity of them or 4-person (which seems excessive) and require 3 or 4.

Some specific suggestions for conflicts of interest.  I feel that the power of friendship/relationship can be very strong.  I think mentor/protege relationships should be barred forever and former co-authors for a susbstantial period - e.g., 5 years ... but I would be happy with longer.

Regarding language, I don't think we want to put non-native speakers at a disadvantage.  Perhaps we can try to find funding on an ad hoc basis for this if the authors plead penury.

**Comment by oostenbrink** [comment]
> If you have suggestions for such software, however, definitely let us know!

The Young Academy of Sciences of Austria uses [https://www.polyas.com/](url), which is quite fancy, but not for free. I think they charge per vote. We payed 64 euro for a vote involving 57 persons, recently. It wouldn't have to be so fancy, though. But I am sure that there are also free solutions, or that we could just use something like surveymonkey or similar.

**Comment by oostenbrink** [comment]
> Regarding appeal of editorial decisions, we want to make that hard. Note that if 2 of 3 'appeal board' editors approve, that's still a 2-2 tie of editors if we include the original one. So in terms of arithmetic we could have a 2-person review and require unanmity of them or 4-person (which seems excessive) and require 3 or 4.

I brought the point up, mostly because it should be clear if there is someone who can overrule. I'm afraid that 'complaints' of unhappy authors happen more often than we may expect and therefore we may also not want to make too big a deal out of it. Personally, I would also be happy with a policy, where a second editor is asked to look at the material and the editors have to come to a joint conclusion. If we really hit an author that could make two editors disagree completely, they can probably still agree on a third editor and then make a majority vote. Any of these solutions can also make a clear message to the authors.

**Comment by dmzuckerman** [comment]
Did we start a document on "Manuscript Review Policies and Procedures" that can address the process and procedural issues in a normal review?  (The current '[Policies about the editorial board](https://livecomsjournal.github.io/policies/editorial_board)' does not address them.)  I assume we are going for a transparent model where, in essence, instructions to editors are also public on the website??

**Comment by davidlmobley** [comment]
@dmzuckerman - not started yet, no, but yes, we should have one. (I am also right now writing a longer response to some fo these issues.)

**Comment by davidlmobley** [comment]
I'll try to answer many of the above at one stroke here. I think I generally agree with what's said above (and thanks, @oostenbrink , for the comments!) so I'll only try to address issues where there might be some disagreement or I disagree slightly.
- **Editorial decisions/appeals**: Seems like two people in addition to the original editor for appeals is good; selected by the lead editor for the category unless that person is the original editor, in which case a different category editor would select. Though Chris's approach is actually simpler and possibly better -- original editor brings in one additional, but if they are divided, they bring in a third as the tiebreaker.
- **Difficult decisions**: For cases of plagiarism, fraud, etc. (maybe the general category is "serious concerns about a previously published article"?), I think we could say that the lead editors will convene an ad hoc committee of editors to investigate and then the commitee will bring the issue before the editorial board for a vote. Does that seem reasonable?
- **Discussion boards**: Totally agree. We're discussing placing a template "code of conduct" for the GitHub repositories in the template repository so that authors would (by default) end up with this in their repositories, but we do not and cannot have any involvement with policing their discussion boards on GitHub.
- **English usage**: I would tend to be inclined to just leave this to the editor overseeing, who will be free to loop in other editors if he/she needs a second opinion. I don't see how to make a firm rule since editing is subjective
- **Voting**: I agree that we'd want to use some kind of voting software typically, though I don't think we want to put WHICH software explicitly into our policies nor even, necessarily, that we will use it.  I agree though that we need to say this is anonymous.
- **Assignment of work to an editor**: Agree with Michael that it would be done by the lead editor of each section
- **Conflicts of interest**: I think it's very hard to define "close friend" so I think we should say that people shouldn't be editors of manuscripts of close friends, close collaborators, or any others for whom they might be perceived as biased, and leave those open to judgment. Except I agree with @dmzuckerman that we should explicitly ban mentor-protege relationships. I disagree with him on this though: " former co-authors for a susbstantial period - e.g., 5 years ... but I would be happy with longer." I'd try to cover that with "close collaborators" -- I've been a co-author with many people I have never even met and hardly (or not at all) interacted with, and the situation may get even worse if more of us co-author papers together as part of LiveCoMS. We don't want to end up in a situation where none of us can edit a given manuscript because we've all been minor co-authors on updates to best practices documents together. :) 



>> The decision making around 'abandoned manuscript' may also call for difficult decisions. In general the authors will want to update a review themselves, but maybe they don't have time. What if there is another person who is eager to take over, but the original authors think they will have time for this in a couple of months (which never comes). Even if a CC-BY license allows for this, I don't think it is considered decent to take a review, modify it (significantly), add your own name to it and republish it. Particularly not if the original authors oppose this idea. We should have some thoughts on how to deal with this.
>
> We have talked about this. And I think we do have to make a firm policy that if it's left alone for some period of time (3 years?), then they have to hand it off if they are not updating. We just can't surprise them with this - they have to expect it. We can clarify this so there is several chances.

There are two issues being addressed together in Michael's response which we should separate. What we're really concerned about (with respect to the succession plan) is when articles NEED updating but are not being updated, in which case we need to plan for a successor. But if an article does not need updating (e.g. no one is raising issues on the issue tracker that are not being resolved) it doesn't need a succession plan unless someone WANTS to keep it alive -- it just needs to be indicated as an article which is no longer "living".

My proposal (*and one I can implement unless there are objections*) is that we:
a) Explicitly say that articles which are not updated for a period of three years will be noted on the LiveCoMS website as no longer "living" (I had thought we had this somewhere in the author guidelines already but I can no longer find it), and that that this would trigger (b)
b) Assess as needed whether existing reviews have become "abandoned" documents which need updating but are no longer being updated (as per "abandoned documents" policy here: https://livecomsjournal.github.io/authors/policies/ ), and add a clause to the instructions indicating how this would be triggered.

In my view we would want clause (b) to be triggered under (a) above, but ALSO if someone complains that a document is not being updated when it should. Our policy already says that we would e-mail the authors AND send a formal letter if there were concerns their document is not being updated, and then would be given **six months** to reply and designate a successor. So to me this seems adequate; the way I imagine it playing out is that someone contacts the editorial board and complains that they proposed some changes on GitHub, say,  eight months ago and the authors still haven't answered, so we send a letter and an e-mail to the authors asking if they are planning to update and to either do so or designate a successor within six months. To me that seems quite reasonable -- if someone isn't going to change ANYTHING for a year or more then it means they should hand it off, typically. (We could allow appeals, of course.)

Probably we can make explicit there might be a two step process here:
1) Someone raises concerns about lack of updates
2) One editor quickly checks if the lack of updates is correct, then if so, quickly contacts the author to check in (maybe it is easily resolved). If no answer in a week, this triggers discussion with at least two other editors, then sending of The Letter.

**Comment by davidlmobley** [comment]
I updated above with an additional comment at the end.

**Comment by davidlmobley** [comment]
On our call of today, we discussed a couple of these:
- Abandoned paper policy; will be updated/clarified exactly when "abandoned" or "archived" document policy may be triggered (two scenarios noted above), and that if ongoing updates are needed they will be given six weeks to (a) designate a successor; (b) have LiveCoMS designate a successor; or (c) decide they are going to update within six months. If they go for option (c) but don't actually do it, we will designate for them following the six months. Also a three year without updates timeline will trigger checking to see if they are abandoned or just need a note that they are "archived" or similar.
- Resolving complaints: We agreed with the suggested "if there's a complaint, bring in a second editor; if there's a tie, bring in a third as a tiebreaker" approach.

**Comment by davidlmobley** [comment]
Also, initially we are concerned with whether they are updating their GitHub repository (where most ongoing maintenance will occur), but we also expect new peer reviewed versions at least every three years.

**Comment by davidlmobley** [comment]
I think this is almost resolved by the bylaws draft, but there are a couple of minor issues lingering:
- [ ] @mrshirts you had mentioned we need a policy on who controls the money, and I don't think we have that yet. Where would it belong? Perhaps we just say that this is managed by the managing editors with editorial approval board approval required for new significant expenses over some dollar threshold (or percentage of cash reserves), or modification of existing expenses if it changes the amount by more than a threshold percentage
- [ ] Need to check that we got the above changes (such as about WHICH documents are being updated) incorporated into bylaws drafts; some probably haven't yet.

**Comment by mrshirts** [comment]
The current bylaws say that the managing editors control the finances.  We'll see if the lawyers at CU have any advice on making that more detailed.

**Comment by mrshirts** [comment]
I believe everything is addressed here.
