### ISSUE TITLE
Rework menu and organization a bit further to ensure it makes logical sense

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#45]
In the header for https://livecomsjournal.github.io/, it lists "policies", and it should probably be "author instructions"

**Comment by davidlmobley** [comment]
There are several other related issues (so I changed the title of the issue to reflect this) about the top menu:
- Currently the menu also has "Editorial Board" which is policies about the editorial board, but this is unclear from its title
- The menu also has "paper writing" ("paper writing as code development") but this probably does not belong there as it is more of a "philosophy statement" than a key piece of info which should be linked at the top

I think the larger issue here is that we're providing several types of information that currently are not clearly distinguished:
a) Actionable information for authors: Overall guidelines for articles, how to submit, etc., as well as information on the specific categories of articles
b) "Philosophical" stuff like "Paper writing as code development" -- probably worth looking at if you're interested in why we're doing thigns this way or are getting ready to manage a GitHub repo, but not actionable
c) Policy information for the journal -- currently mainly "Editorial Board"

We probably want to rethink the design a bit to clearly distinguish these. I'd suggest the following action items:
- [ ] Redo the header so it all fits on one page, with something like "Author instructions", "Category-specific instructions" (which would go to a page which has links to the overall instructions and the instructions on each specific category of article), "About our model" (which would link to the "why LiveCoMS" document on the journal site), and "Editorial Policies" (which would link to the editorial board information, the identity of the editorial board (on the other website) and anything else policy-oriented we eventually need to add)
- [ ] Decide whether there are other policy documents we need?
- [ ] Rework the main (entry) page to have something more useful and visually appealing rather than just a list of what is on the site. Maybe this should be a very concise summary of the journal with an image, plus a short list of categories of info? Perhas just "Author instructions", "About our model", and "Editorial Policies", which would then themselves link to the subpages? 
- [ ] Currently the main page subtitle says "Submission, review, and editorial policies" as a summary of what's on the site, but this does not seem complete; maybe it should be "Author instructions and journal information" to provide more of a catch-all term?
- [ ] Currently the blurb about the site on the main page says it "details the submission, review, and editorial policies of ..." but again this is perhaps too narrow. Maybe, "... provides author instructions and policy and journal information for ..."?

**Comment by davidlmobley** [comment]
@mrshirts @dmzuckerman thoughts on the above? Trying to think through overall layout and how to make it make sense.

**Comment by davidlmobley** [comment]
Reading through issues, I also arrive at #1 which brings me to again think, maybe we need two separate sets of info for authors:
- INSTRUCTIONS for authors, which very briefly summarizes what to do, where, and how, with links, perhaps using even a checklist format. This would be much more brief than our current https://livecomsjournal.github.io/policies/ page
- Information for authors, as we currently have at https://livecomsjournal.github.io/policies/

Thoughts? Or maybe this is overkill. I just worry that we don't currently have any actual instructions to follow for getting started, such as:
0) Submit a presubmission inquiry (as per these instructions (link)) to ... ; after approval:
1) Go to github.com/livecomsjournal/article_templates, click (whatever) and then click (fork) or whatever, and follow the instructions in (this file)
2) ...
3) Write a cover letter, and submit your cover letter and PDF and the names of N reviewers by visiting ... 
4) ... 

Right now getting started would involve someone reading our guidelines, and then figuring out that there is a repo somewhere which has template files (I don't think this is obvious at present) and that there are instructions there they can follow to mirror the repo, and then....

**Comment by dmzuckerman** [comment]
See ***

I think the larger issue here is that we're providing several types of information that currently are not clearly distinguished: ...  We probably want to rethink the design a bit to clearly distinguish these.

*** Agreed.

I'd suggest the following action items:

  *   Redo the header so it all fits on one page, with something like "Author instructions", "Category-specific instructions" (which would go to a page which has links to the overall instructions and the instructions on each specific category of article), "About our model" (which would link to the "why LiveCoMS" document on the journal site), and "Editorial Policies" (which would link to the editorial board information, the identity of the editorial board (on the other website) and anything else policy-oriented we eventually need to add)

*** Makes sense.  Perhaps 'General author instructions' to parallel category-specific

  *   Decide whether there are other policy documents we need?
  *   Rework the main (entry) page to have something more useful and visually appealing rather than just a list of what is on the site. Maybe this should be a very concise summary of the journal with an image, plus a short list of categories of info? Perhas just "Author instructions", "About our model", and "Editorial Policies", which would then themselves link to the subpages?

*** Concise summary (one or two sentences) plus the three categories sounds good.  Maybe 'About LiveCoMS' instead of 'about our model'

  *   Currently the main page subtitle says "Submission, review, and editorial policies" as a summary of what's on the site, but this does not seem complete; maybe it should be "Author instructions and journal information" to provide more of a catch-all term?

*** works for me

  *   Currently the blurb about the site on the main page says it "details the submission, review, and editorial policies of ..." but again this is perhaps too narrow. Maybe, "... provides author instructions and policy and journal information for ..."?

*** ok
________________________________

**Comment by ptmerz** [comment]
A few thoughts:

Header:
* I *really* like the idea of having 3 categories with subpages as suggested by @davidlmobley, and I agree that it's necessary. When re-organizing the webpage, it did indeed feel a bit unorganized to add all 7 pages like I did, but I left it like that for lack of a better idea.
* The header in this theme is flexible - the wider the browser window, the more categories are displayed. I think that having only 3 should allow to have them fully displayed in most reasonable circumstances. Keeping the category titles short will also help.

Start page:
* Agreed that it could be visually more appealing. I could imagine to keep the layout of the upper part of the current page (eventually replace the splash image when we have a nice visualization, improve the subtitle, replace or expand the "blurb about the site on the main page" with the "very concise summary of the journal"), and adding the three categories in a style similar to the main page of https://mmistakes.github.io/minimal-mistakes/. I used this style first for the main page, but it looked too crowded having 7 categories on the page, hence the list - but I think that with the 3 discussed categories that should look better.

From a jekyll / theme point of view, these changes should be doable. If there is agreement on these points, I'm happy to give it a try.

**Comment by ptmerz** [comment]
Concerning the author instructions - maybe the current https://livecomsjournal.github.io/policies/ could simply be prefaced with a numbered list as proposed by @davidlmobley, linking to the sections of the file? A best-practice document on publishing best-practice documents, so to say :)

**Comment by davidlmobley** [comment]
I just revisited this to think through where things stand. The recent revisions (thanks @ptmerz !) helped a lot but I still have the issue that we don't actually have INSTRUCTIONS for authors anywhere. So, when I can work on this next, I plan to reformat the page `https://livecomsjournal.github.io/authors/` into a short intro followed by a numerical list which links out to the various different components of the instructions in the order in which authors should follow them.
