### ISSUE TITLE
Preprints - did we decide?

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/livecomsjournal.github.io#48]
@dmzuckerman @mrshirts - currently the author instructions still say they post to a preprint server of their choice prior to submission. I believe we said that this isn't strictly necessary? Specifically, we will be hosting a PDF of the article on the LiveCoMS site, so I think it should be their business if they use a preprint server or not. 

I'll make a PR which would update the language accordingly, but LMK if I'm off base.

**Comment by dmzuckerman** [comment]
Since we are not using reviewing or publishing based on a preprint server, this seems right.  Then we are no longer an 'overlay' journal ... another thing to check for.  Let's see what Michael says.

If we are not requiring a preprint server, we should at least say it's allowed.  Encouraged??
________________________________

**Comment by davidlmobley** [comment]
I did say it's allowed. I'm not sure if we want to say "encouraged" -- they also have it on their GitHub repo, so some authors might view this as an unnecessary extra step. But I'm also fine with encouraging it...

**Comment by mrshirts** [comment]
I think we encourage, for their intermediate version to be considered, but not require.

Though it might be problematic for bioRxiv, where you apparently can't revise once it's published.

**Comment by mrshirts** [comment]
So perhaps we "welcome" them to submit to a preprint archive, rather than encourage.  The text you have in one of the PR's seems fine.
