### ISSUE TITLE
What additional/different overall author instructions are needed?

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#62]
Comment thread.

**Comment by hmayes** [comment]
Do we need to comment on references? The LaTex template files include a sample .bib and a .bst file. Do we want to provide more instruction to help ensure consistency? Do we want to make a note to check that special characters appear correctly; that titles should appear in title case; use journal name abbreviations or not?

**Comment by davidlmobley** [comment]
@hmayes - right on target. So we'll add:
- [ ] Info on using bst
- [ ] Info on formatting of references, including that they should use journal abbreviations and Title Case, and a reminder to check special characters

**Comment by hmayes** [comment]
Sounds great! I also suggest we add "\usepackage{natmove}" to the template, so we don't have to deal with inconsistencies between "\cite" added before or after commas and periods. I'll put that comment in to the template issues.

**Comment by dmzuckerman** [comment]
Figure permissions instructions needed - to republish in Livecoms.  We will be featuring reviews and best practices articles which often will re-use figures from literature.  We need language/info for authors to do this easily.  @davidlmobley @mrshirts - will we need to do more than specify journal and license?  BTW I could use guidance right now for my group's best practices doc!  Thanks.

**Comment by mrshirts** [comment]
Good point. I will put this on the list of things to address with lawyers (we can now use CU lawyers to answer these questions now that the provost approved it).  

I should make a lawyer question issue. . .

**Comment by oostenbrink** [comment]
Just some thoughts on how we write the general instructions. I'm trying to put in my experience on reading such instructions. Most people don't take the effort to really read this, but they browse through and think that they have seen it.
- At the top, where we have the specific links to the 'Types of Articles'. I guess it would be nice if there is a one line explanation what each of these are. Not everyone will immediately understand the difference between 'best practices' and 'lessons learned'.
- Under the heading 'writing style and editing', I would suggest to shift the paragraph 'It is particularly important to note' to be the second sentence of this section. We will want people to be aware of this and most readers will stop reading somewhere at the third bullet point thinking 'yeah yeah, makes sense'.
- Under the heading 'Review criteria' we write "Authors whose article uses inconsistent style or poor grammar, or is poorly edited, may be asked to revise and address these issues" What happens if we don't reach an agreement? (Maybe more an issue for the 'editorial policy'
- Under 'Authorship and Changes to Authorship', there is a 'listed listed'.
- Under the heading 'prior publication', we write "e.g. Annual Reviews, lets the authors retain the right to create derivative works, which could perhaps be exercised in preparing a review to be published in LiveCoMS." Is there any risk that Annual Reviews does not appreciate that we actively call for recycling their reviews (even if it is allowed). Consider removing the 'e.g. Annual Reviews'
- Under the heading 'prior publications', there is a paragraph on author orders. Shouldn't this be under the heading for 'Authorship' ? Furthermore, what do we mean with "Authors should, to the extent possible, determine the author order among themselves." Of course this is the case. When is this no longer possible, and who decides then? I don't think an editor will want to make decisions here.
- The point about 'Abandoned manuscripts' will call for some difficult decisions. We cannot force authors to make an update (no time, no real interest), and then there should be very clear rules if others are to take over. Even if this is allowed within the CC-BY license, I have a hard time enforcing it. Who decides that now is the time for an update? When did an author get enough friendly suggestions? Do we actively search for an alternative author to take over? I'm not worried about the people leaving science, I am worried about the people who don't have time for anything but will still be very unhappy to pass things on, because everyone always thinks he/she will have plenty of time next month.

**Comment by mrshirts** [comment]
- At the top, where we have the specific links to the 'Types of Articles'. I guess it would be nice if there is a one line explanation what each of these are. Not everyone will immediately understand the difference between 'best practices' and 'lessons learned'.

Could you be a little more specific?  Right now, when you go to a page like: https://livecomsjournal.github.io/authors/best_practices/
it does state at the beginning what it is.  HOWEVER, only the heading "what is a . . .  " appears at the top level: https://livecomsjournal.github.io/authors/
We could try to reorganize it so something else appears there instead of the initial question: we could just start with the definition.


- Under the heading 'writing style and editing', I would suggest to shift the paragraph 'It is particularly important to note' to be the second sentence of this section. We will want people to be aware of this and most readers will stop reading somewhere at the third bullet point thinking 'yeah yeah, makes sense'.

I will propose a change.

> - Under the heading 'Review criteria' we write "Authors whose article uses inconsistent style or poor grammar, or is poorly edited, may be asked to revise and address these issues" What happens if we don't reach an agreement? (Maybe more an issue for the 'editorial policy'

Yeah, we'll have to reach an agreement on this. 

> - Under 'Authorship and Changes to Authorship', there is a 'listed listed'.

Will fix. 

> Under the heading 'prior publication', we write "e.g. Annual Reviews, lets the authors retain the right to create derivative works, which could perhaps be exercised in preparing a review to be published in LiveCoMS." Is there any risk that Annual Reviews does not appreciate that we actively call for recycling their reviews (even if it is allowed). Consider removing the 'e.g. Annual Reviews'

Good idea. Also, the lawyer is going to give us some info on what to say there anyway. But we can remove Annual Reviews.

> Under the heading 'prior publications', there is a paragraph on author orders. Shouldn't this be under the heading for 'Authorship' ? Furthermore, what do we mean with "Authors should, to the extent possible, determine the author order among themselves." Of course this is the case. When is this no longer possible, and who decides then? I don't think an editor will want to make decisions here.

Maybe "Authors must decide themselves?". The one exception I can think of is if an author is no longer participating -- but even then, the remaining authors must the decide. A situation that could occur is if one author emails us to complain about authorship after the article is submitted.  The policy would seem to dictate that we would not review the article until the authors had agreed. I suppose a previous author could keep an article from being published at all (or even another person could keep it from being published).  

If someone claims authorship, after the initial submission at least, they should appear in the GitHub log. So it should be more straightforward to address whether someone is an author or not.  Author order is another thing -- but once someone is established as an author, then placement is easier to work out. We should encourage people to get it working on GitHub when they start so we do have a record.

~~The point about 'Abandoned manuscripts' will call for some difficult decisions. We cannot force authors to make an update (no time, no real interest), and then there should be very clear rules if others are to take over. Even if this is allowed within the CC-BY license, I have a hard time enforcing it. Who decides that now is the time for an update? When did an author get enough friendly suggestions? Do we actively search for an alternative author to take over? I'm not worried about the people leaving science, I am worried about the people who don't have time for anything but will still be very unhappy to pass things on, because everyone always thinks he/she will have plenty of time next month.~~
Some discussion of this already policies. I think what we will need is a clear policy that it CAN be continued if they don't. Some clarification might be useful, I can work on that.

**Comment by mrshirts** [comment]
OK, submitted a PR (https://github.com/livecomsjournal/livecomsjournal.github.io/pull/76) to address some of the more simply resolved comments.

**Comment by oostenbrink** [comment]
> At the top, where we have the specific links to the 'Types of Articles'. I guess it would be nice if there is a one line explanation what each of these are. Not everyone will immediately understand the difference between 'best practices' and 'lessons learned'.

> Could you be a little more specific? Right now, when you go to a page like: https://livecomsjournal.github.io/authors/best_practices/
it does state at the beginning what it is. HOWEVER, only the heading "what is a . . . " appears at the top level: https://livecomsjournal.github.io/authors/
We could try to reorganize it so something else appears there instead of the initial question: we could just start with the definition.

Indeed, this is what I meant. The line 'What is a ..." right under the link is not very helpful. If there is a one liner to give some guidance, that would help. This could also be the heading of the actual page.

Similarly, at [https://livecomsjournal.github.io/authors/policies/](url) under the heading 'Article types', there is a series of links to the individual groups. The same definitions could be given right under them?

**Comment by davidlmobley** [comment]
I addressed a policy-related part fo this here: https://github.com/livecomsjournal/livecomsjournal.github.io/issues/31#issuecomment-338343958

I'll have to revisit the rest later.

**Comment by davidlmobley** [comment]
Just for the record, the current class does use natmove automatically.

I've made sure the other action items listed here are all resolved, except that I will open a PR to comment on references in the author instructions, and I've noted to update the templates with information on proper reference style as well.

**Comment by hmayes** [comment]
Great! Thanks.

**Comment by davidlmobley** [comment]
Lingering issues here (relating to guidance on references) should be resolved by #105 ; @hmayes , want to do a quick check?
