### ISSUE TITLE
Webpage 'About LiveCoMS'

### ISSUE THREAD

**Issue by dmzuckerman** [livecomsjournal/livecomsjournal.github.io#78]
Currently, there are two versions of the 'about' webpage, and neither is quite right I think:
- [on the web](http://www.livecomsjournal.org/about) 
- [on github](https://livecomsjournal.github.io/about/)

Suggestions:
- We want the text that's on the web version EXCEPT that the second paragraph should perhaps be deleted because we won't technically be an overlay journal - nicely formatted pdfs will come from Scholastica.
- We should link our ['why livecoms' editorial](http://www.livecomsjournal.org/article/2031-why-we-need-the-living-journal-of-computational-molecular-science) as a more in-depth discussion.
- I'm not sure if we need to link 'Paper writing as code development' directly unless its mentioned in revised 'about' text.

**Comment by davidlmobley** [comment]
@mrshirts - can you address this? Or at least, the web version needs correcting. Once corrected I'm happy to add that info to the GitHub one also.

**Comment by mrshirts** [comment]
We deleted the text about the overlay journal a couple of PR's ago.  I just added  #134 to make the web one include the same information as on the web site for now.  I'm leaving the "paper writing as code development" in for now - it's fits better an an additional item rather than the first thing one sees.
