### ISSUE TITLE
Add bylaws describing how editorial board runs, and how we run review process, etc.

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#83]
Looking over other journals and organizations, it would be good to put some standard bylaws into place.  There's two types: full non-profit, and just journal ones. 

We probably want something more low scale for now, but the fuller ones can give some idea.

An example of more full bylaws from Public Library of Science.

[PLOS bylaws](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1418836/PLOS-Bylaws-Amended-5-18-13.pdf)

Several journal bylaws, with a range of detail but a lot of commonality. that we should include

[CALA International Journal of Librarianship](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1418827/2016_rpt_interim_tf_OAAJTF_attach3.pdf)

[Harvard Journal on Legislation](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1418817/JOL-Bylaws.pdf)

[BYU Education and Law Journal](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1418815/bylaws.2010.pdf)

[Journal of International Organization](https://github.com/livecomsjournal/livecomsjournal.github.io/files/1418813/BYLAWS.OF.THE.JOURNAL.OF.INTERNATIONAL.ORGANIZATIONS.STUDIES.pdf)

**Comment by dmzuckerman** [comment]
Perhaps we want something based on CALA and BYU - to keep the focus on the rules needed for running the journal - especially as we are not tied to an external organization.  It seems we can get away with a single document on 'Bylaws and Editorial Procedures'.

**Comment by mrshirts** [comment]
I think the bylaws would then become the editorial board procedures.  We probably would still want a "review process" page, but that's just description of what happens, no internal policy involved.

**Comment by mrshirts** [comment]
OK, posted draft bylaws at https://github.com/livecomsjournal/livecomsjournal.github.io/pull/85. Still a lot of work needed!

**Comment by hmayes** [comment]
Reviewing this now. I'm making some minor edits (e.g., removing a repeated phrase). Some questions:

1) In the selection process, I would like to see more information about selected versus elected. Managing editors and section lead editors are to be elected; that seems clear. Let's specify who will select the temporary vacancies in the section lead editors, and who selects the associate editors.  Is specifying how all members of the editorial board, and managing editors, appropriate, if they are elected?

2) Do we want to be less strict in the conflicts of interest (e.g. 36 months instead of 48)? How do we want to define a business relationship? For example, can someone on the editorial board review a paper written by another editorial board member? That is, do we consider serving on an editorial board "business", or only if financial gain is involved?

3) In terms of "bias", I added "unduly" in a slight nod to the fact that we all have bias, all of the time (we just can't help it by being human). We just don't want it to turn into unjust treatment (accept paper that did not merit it, or reject one that did).

4) Perhaps a question for the lawyer: Do we need to specify how elections will take place? E.g., at any meeting of the editorial board (to allow for regular meetings or special meetings to appoint editors). 

5) I don't fully flow the voting on amendments; the board will be given 1 week's notice that they won't have a week to vote?

**Comment by hmayes** [comment]
For the "reviewing" doc, we'll need to be careful to ensure consistency with the bylaws; think we are okay now.

**Comment by davidlmobley** [comment]
@hmayes -- where are you proposing the edits you mentioned?

**Comment by hmayes** [comment]
Meant these comments to go to #86. Your response covered many of my
concerns. Thanks.

**Comment by mrshirts** [comment]
If anyone has grammar corrections (or proposed change for other things!) those can be submitted directly as a PR to the PR.  That will speed the process, since it doesn't require me re-doing all the changes.

Probably better to submit grammar changes and substantive changes separately in case there are discussions needed to for those.  

And as mentioned; this PR is something that needed to get posted so we could have these discussions; I'm not particularly set on anything.

**Comment by davidlmobley** [comment]
Sorry for the confusion. Probably we should address GitHub protocol -- naively I was expecting that if you just wanted to discuss, you would either have up a "[WIP]" PR or just have it in a branch that you would link to in an Issue on the topic for discussion, whereas a PR without "[WIP]" to me (especially one where you request a review) means "I'm ready to merge this so please check it before I do so." That's why I provided such detailed comments.

Definitely agree that we need more discussion of this.

**Comment by mrshirts** [comment]
Title of the PR changed :).  I put in the initial description that it was just a first pass, but did not think of putting WIP in the title. I'm not a very much 'by fiat' guy, you should know by now (which is why some decisions are happening slowly!)  There was already an issue listed, apologies for not crossreferencing more.

**Comment by mrshirts** [comment]
Addressed by #86
