### ISSUE TITLE
Defining a COI

### ISSUE THREAD

**Issue by mrshirts** [livecomsjournal/livecomsjournal.github.io#87]
The WIP bylaws are currently. 
Conflicts of interest
    1. A 'conflict of interest' is defined as any of:
       a. being a co-author on a paper together for up to 48 months after publication
        b.  co-awardee on a grant for up to 48 months after the grant, or that currently have a cooperative pending grant.
        c. if there exists a postdoctoral or graduate advisor relationship at any time in the past.
        d.  at the same institution, or if there is a potential change of institution in progress that would result in being at the same institution.
     e.  having a business relationship (such as serving as a consultant for or part owner of same company) within 48 months.

Comments are:

dlmobley:
I still think this "co-author of a paper" is far too restrictive, especially since as part of LiveCoMS we will likely (and hope to) see papers with more of us co-authoring with one another. It has the advantage that it is easy to judge, but I also think it is too broad. I've co-authored with many people I have never even met and would not be biased about reviewing for, and there are people I would perhaps be more biased about reviewing for whom I've never co-authored with.

dmzuckerman:
I think Heather also thought this was too strict, and I guess the idea was mine. What's a reasonable compromise? Can we define a more restrictive term like 'close authorship' which could mean you and the author were either (co)first or (co)corresponding authors. Should we just leave it up to the editor and have them upload a statement as to why they are not biased if there is co-authorship? (Do we have a way to add statements to the review record? Does Scholastica have a review record??)

dlmobley:
I worry this will preclude any of us ever publishing in LiveCoMS; we've all co-authored with one another (or almost all -- I've not co-authored with Piquemal yet but he looks likely to be a co-author on one of the best practices documents I'd be on...). Who will serve as Lead Editor if I submit a paper?

I'm just very worried that the conflict policies, especially with regards to co-authorship, are going to be impractically broad ESPECIALLY if LiveCoMS ends up being successful in bringing together the community in best practices documents. I think what we WANT is to encourage people to co-author documents as much as possible to improve them (though they'll have to worry a bit about who will be able to review their NSF proposals). Do we really want to provide people with an extra incentive NOT to contribute to improving these documents in order to ensure they have editors and reviewers?

I just think we need to move to a narrower definition of what constitutes a conflict, and I also think this especially appropriate given the mechanisms for live updates/community feedback that LiveCoMS provides. Yes, we want peer review quality to be high, but there is also ample opportunity to improve things post peer-review which there isn't normally.

dmzuckerman: 
I have proposed a narrower definition above. But we do need to avoid COIs. We can't be seen as a community publishing our own papers - printing academic money, so to speak!

hmayes:
Do we want to be less strict in the conflicts of interest (e.g. 36 months instead of 48)? How do we want to define a business relationship? For example, can someone on the editorial board review a paper written by another editorial board member? That is, do we consider serving on an editorial board "business", or only if financial gain is involved?

**Comment by davidlmobley** [comment]
I like what Dan is thinking here:
>  Can we define a more restrictive term like 'close authorship' which could mean you and the author were either (co)first or (co)corresponding authors. Should we just leave it up to the editor and have them upload a statement as to why they are not biased if there is co-authorship? (Do we have a way to add statements to the review record? Does Scholastica have a review record??)

I think the approach I'd **like** to see, if it's acceptable to others, is that enumerate common causes of conflicts of interest SUCH AS close authorship, collaboration, etc., and then:
a) Have editors assess whether they think one of these *potential* conflicts applies to reviewers they are thinking of 
b) Have the "request for review" form which goes to reviewers include a link to the potential conflicts of interest and ask them to decline if they have an ACTUAL conflict due to any of these potential reasons

We could also:
c) Have the presubmission letter (or submission letter?) include a list of people who should be excluded as reviewers because of a conflict of interest

If we do that we'd have three levels of checks on the process: Editorial, reviewer, and author.

While this is unappealing from a "firm rules" point of view, I like it because I think ultimately, many conflicts (though not those involving previous supervisors or financial interests) are ultimately subjective -- I can have a much larger COI concerning someone I just happen to be close with than I do concerning a co-author, for example, even though the former isn't on the list of COIs we can check.

**Comment by dwsideriusNIST** [comment]
I'll echo David's comment:

> While this is unappealing from a "firm rules" point of view, I like it because I think ultimately, many conflicts (though not those involving previous supervisors or financial interests) are ultimately subjective -- I can have a much larger COI concerning someone I just happen to be close with than I do concerning a co-author, for example, even though the former isn't on the list of COIs we can check.

If we try to define it firmly and objectively, the policy cover too many edge cases that are not relevant COIs. Using general guidelines will be more effective that strict definitions; provide lists of possible COIs and then ask people to recuse themselves.

What keeps coming to my mind is that it's really difficult to define a COI, but "I know it when I see it ..."

**Comment by mrshirts** [comment]
> c) Have the presubmission letter (or submission letter?) include a list of people who should be excluded as reviewers because of a conflict of interest

This could be a little unwieldy, since the people don't know who all the potential reviewers are, and we don't want them listing all of the COI's like for an NSF grant.

So 
> a) Have editors assess whether they think one of these potential conflicts applies to reviewers they are thinking of
> b) Have the "request for review" form which goes to reviewers include a link to the potential conflicts of interest and ask them to decline if they have an ACTUAL conflict due to any of these potential reasons

Seem pretty reasonable.

**Comment by mrshirts** [comment]
So, I think the only places to definitely restrict thing is to define "close" co-authorship to be close collaborators, and leave that up to the reviewer.  Perhaps we have the reviewer document any authorship, and decide for themselves on close authorship, and the editors approve.  

For the editors: perhaps they report to the Section Lead, and the section lead approves?  For the section lead, then it's a bit more complicated, since there's only the managing editors to approce.

**Comment by davidlmobley** [comment]
> This could be a little unwieldy, since the people don't know who all the potential reviewers are, and we don't want them listing all of the COI's like for an NSF grant.

On the other hand, my view of the NSF one is that these are excessive. Specifically, again, I have to list for NSF everyone I've co-authored with in the last X years. I don't even know some of these people's names, much less who they are!! (e.g., we contribute some modeling work to an experimental guy's paper, and his experimental collaborator in country Y had a grad student who did something which led to them being a co-author on the paper -- so they're my co-author, but I don't even know who they are.) 

I'd be much happier submitting a list of people who I think actually have a conflict of interest with respect to my work (since it would be fairly short) than a list of everyone I've co-authored with.

>So, I think the only places to definitely restrict thing is to define "close" co-authorship to be close collaborators, and leave that up to the reviewer. Perhaps we have the reviewer document any authorship, and decide for themselves on close authorship, and the editors approve.

Sounds good to me. I think we just want to be descriptive and ask them to disclose anything which might affect their fairness in the review process, or be perceived as others as something which MIGHT affect tehir fairness, and list a bunch of common potential conflicts. Then they disclose and we decide.

> For the editors: perhaps they report to the Section Lead, and the section lead approves? For the section lead, then it's a bit more complicated, since there's only the managing editors to approce.

Yes, probably should just go up the chain, but then if we run out of "up" the the person in question has to find an associate editor without a conflict who can evaluate.

**Comment by davidlmobley** [comment]
A lot of this is dealt with in the draft bylaws, #86 .

**Comment by davidlmobley** [comment]
Marking as closed as I think the draft resolves this; we can reopen if needed.
